sudo: required
before_install:
- git clone https://github.com/KiCad/kicad-library-utils /home/travis/build/kicad-library-utils
- git clone https://github.com/KiCad/kicad-library /home/travis/build/kicad-library-old

script:
- sudo bash ./library-check.sh $TRAVIS_BUILD_DIR