sudo: required
before_install:
- git clone https://github.com/KiCad/kicad-library-utils
- git clone https://github.com/KiCad/kicad-library
- sudo mv kicad-library /usr/local/share/kicad-library
- sudo mv kicad-library-utils /usr/local/share/kicad-library-utils

script:
- library-check.sh
- python /usr/local/share/kicad-library-utils/schlib/checklib.py -v ./library/*